version: "3.4"

services:
  caddy:
    container_name: app1

    build:
      context: .
      target: caddy

    networks:
      - main_network

    restart: always

networks:
  main_network:
    external: true
