version: "3.4"

services:
  caddy:

    container_name: main_caddy

    build:
      context: .
      target: caddy

    ports:
      - "80:80"
      - "443:443"

    networks:
      - main_network

    restart: always

networks:
  main_network:
    external: true
